### ISSUE TITLE
Create a 'show' page for each library item

### ISSUE THREAD

**Issue by kwilcox** [asascience-open/larva-library#10]
accessible as a GET request to /library/1, it should represent the Library item in its entirety.

**Comment by CowanSM** [comment]
Most-of-the-way there. Missing a few items due to the wizard not being fully implemented

**Comment by CowanSM** [comment]
Implemented, will have to be changed once geo-positional and lifestages data fields are more accurate in their presentation. Also it is butt-ugly.

**Comment by kwilcox** [comment]
Make this /library/detail/{{name}}

http://flask.pocoo.org/docs/quickstart/#variable-rules

**Comment by kwilcox** [comment]
now that i think about it, people will enter strange things for a name.  Let use the ID

@app.route('/ObjectId:library_id')

you can access the id field by doing library_object._id

**Comment by CowanSM** [comment]
ID is being used
