### ISSUE TITLE
Retrieve JSON list of library items

### ISSUE THREAD

**Issue by kwilcox** [asascience-open/larva-library#12]
/library.json should return a list of library items for use in external applications

**Comment by CowanSM** [comment]
making note: this list includes entries they own plus entries owned by the master list (or whatever the public user is)

**Comment by kwilcox** [comment]
as discussed, this will take an email address as a parameter and return public entries as well as entries owned by that user

**Comment by CowanSM** [comment]
lists all 'public' entries and those owned by the user. prints the json for each entry returned as such.
