### ISSUE TITLE
Retrieve JSON list of library items from keyword search

### ISSUE THREAD

**Issue by kwilcox** [asascience-open/larva-library#13]
/library.json?terms=xxxx,yyyy should return a list of library items for use in external applications, subset by items matching the internal search on "terms"

**Comment by CowanSM** [comment]
making note: similar to #12, this list includes the user's list plus master/public list

**Comment by kwilcox** [comment]
as discussed, this will take an optional email address as a parameter so search the users private library items

**Comment by CowanSM** [comment]
right now it uses the currently logged in user's username (if they are logged in it should be their email) to search for their 'private' entries, is this good enough?

**Comment by CowanSM** [comment]
Implemented as requested. waiting for approval before closing task (see pull request).

**Comment by kwilcox** [comment]
all set
