### ISSUE TITLE
Uploading of config file

### ISSUE THREAD

**Issue by kwilcox** [asascience-open/larva-library#22]
A library item that is downloaded should be able to be uploaded into the system.

this should be a link next to "create a new library entry" that says "upload a library file"

a dialog should be presented and the user can select a library file.

There has to be some checking to make sure it is a library file (the contents are OK).

This should always create a new entry.  Since the "name" of a library is unique, it may have to be incremented by one (add a number to the end of the uploaded 'name' field).

**Comment by CowanSM** [comment]
importing libraries works fine, just fine
