### ISSUE TITLE
Create library model with basic information

### ISSUE THREAD

**Issue by kwilcox** [asascience-open/larva-library#7]
-  Name user defined - (unicode)
-  Genus (unicode)
-  Species (unicode)
-  Common name (unicode)
-  Keywords (list of unicode)
-  GeoKeywords (list of unicode)
-  Geometry (unicode) Note: mongodb only supports "point" geometries, so we will store a WKT string
-  Lifestages (TBD, probably a list of dicts)
-  created_at - datetime

For reference: http://namlook.github.com/mongokit/structure.html and the User model

**Comment by CowanSM** [comment]
Finished basic model with previous commit. Created_at is still in aether since the datetime was causing crashes on the server.
