### ISSUE TITLE
Create entry forms for Library model

### ISSUE THREAD

**Issue by kwilcox** [asascience-open/larva-library#8]
For reference:
-  http://packages.python.org/Flask-WTF/
-  http://flask.pocoo.org/docs/patterns/wtforms/
-  The sketch on Lima

Good to keep in mind that these will need to be editable in the future

**Comment by CowanSM** [comment]
Need some help on this one. Particularly regarding the life stages and how to generate a number of entry forms based on user input. Also may need to review the geographic position input as I kinda forgot how that was suppose to look.

**Comment by kwilcox** [comment]
We'll stop at lifestages, I Created a new ticket for the geographic position
