### ISSUE TITLE
Create a 'list' page to list all library entries

### ISSUE THREAD

**Issue by kwilcox** [asascience-open/larva-library#9]
This should list (in a table format) all all of the library documents, showing their:
-  name
-  genus
-  species
-  common name
-  the date it was created

**Comment by CowanSM** [comment]
Currently all entries owned by the user are shown (name only) with a detail and edit links that will do as they say. Basic searching is also in.

**Comment by CowanSM** [comment]
Just made a push to issue_#9 branch that should close this issue.
